apps/app/lib/app_web/router.ex
defmodule AppWeb.Router do
  use AppWeb, :router
  use Pow.Phoenix.Router

  use Pow.Extension.Phoenix.Router,
    extensions: [PowResetPassword, PowEmailConfirmation]

  import Phoenix.LiveDashboard.Router

  alias Legendary.AuthWeb.Plugs.RequireAdmin

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(:put_layout, {AppWeb.LayoutView, :app})
    plug(:put_root_layout, {AppWeb.LayoutView, :root})
    plug(AppWeb.Plugs.TempUserId)
    plug(AppWeb.Plugs.FetchCart)
    plug(AppWeb.Plugs.FetchParticipatingRuns)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :require_admin do
    plug(RequireAdmin)
  end

  pipeline :require_organizer do
    plug(AppWeb.Plugs.RequireOrganizer)
  end

  pipeline :require_auth do
    plug(Pow.Plug.RequireAuthenticated, error_handler: Pow.Phoenix.PlugErrorHandler)
  end

  # Other scopes may use custom stacks.
  # scope "/api", AppWeb do
  #   pipe_through :api
  # end

  if Mix.env() in [:dev, :test] do
    forward("/sent_emails", Bamboo.SentEmailViewerPlug)
  end

  scope "/" do
    pipe_through([:browser, :require_auth, :require_admin])

    live_dashboard("/live-dashboard", metrics: AppWeb.Telemetry)
  end

  if Mix.env() == :e2e do
    forward("/end-to-end", Legendary.CoreWeb.Plug.TestEndToEnd, otp_app: :app)
  end

  scope "/" do
    pipe_through(:browser)

    pow_session_routes()

    get "/signup", AppWeb.RegistrationController, :new
    post "/signup", AppWeb.RegistrationController, :create

    # Don't ask why this is called :show.
    get "/confirm-email/:token", AppWeb.EmailConfirmationController, :show,
      as: :pow_email_confirmation_confirmation

    get "/reset-password/new", AppWeb.ResetPasswordController, :new,
      as: :pow_reset_password_reset_password

    post "/reset-password", AppWeb.ResetPasswordController, :reset

    get "/reset-password/:token", AppWeb.ResetPasswordController, :edit
    put "/reset-password/:token", AppWeb.ResetPasswordController, :save_new_password
  end

  scope "/" do
    pipe_through(:browser)

    get("/search", AppWeb.SearchController, :index)
    get("/search/:query", AppWeb.SearchController, :index)
    get("/cart", AppWeb.CartController, :index)
    post("/cart", AppWeb.CartController, :update)
  end

  scope "/" do
    pipe_through(:browser)
    pipe_through(:require_auth)

    get("/account", AppWeb.AccountController, :index)
    get("/account/edit", AppWeb.AccountController, :edit)
    put("/account", AppWeb.AccountController, :update)

    resources("/addresses", AppWeb.AddressController)

    get("/order", AppWeb.OrderController, :index)
    get("/order/:id", AppWeb.OrderController, :show)

    resources("/runs", AppWeb.RunController)

    get("/join/:uuid", AppWeb.JoinController, :join)
    delete("/join/:uuid", AppWeb.JoinController, :leave)
    get("/my-runs", AppWeb.JoinController, :index)

    post("/billing/checkout", AppWeb.BillingController, :checkout)
  end

  scope "/" do
    pipe_through(:browser)
    pipe_through(:require_auth)
    pipe_through(:require_organizer)
  end

  use Legendary.Core.Routes
  use Legendary.Admin.Routes
  use Legendary.Content.Routes
end

apps/app/lib/app_web/controllers/search_controller.ex
defmodule AppWeb.SearchController do
  @moduledoc """
  Implements the main product search through the big search bar.

  Must run after `AppWeb.Plugs.FetchCart`.
  """

  use AppWeb, :controller

  alias App.Catalog

  def index(conn, params) do
    query =
      case params do
        %{"search" => %{"query" => query}} ->
          # URLs like "/search?search[query]=fentimans"
          query

        %{"query" => query} ->
          # URLs like "/search/coca+cola"
          query

        _ ->
          ""
      end

    cart_lines =
      for cart_line <- conn.assigns.cart_lines, into: %{} do
        {cart_line.product_id, cart_line}
      end

    products =
      for product <- Catalog.query_products(query) do
        Map.put(product, :cart_line, Map.get(cart_lines, product.id))
      end

    render(conn, "index.html", query: query, products: products)
  end
end

apps/app/lib/app_web/views/search_view.ex
defmodule AppWeb.SearchView do
  use AppWeb, :view
end

apps/app/lib/app_web/templates/search/_search_bar.html.eex
<% conn_or_socket = if assigns[:conn], do: assigns[:conn], else: @socket %>
<% query = if assigns[:query], do: assigns[:query], else: "" %>

<section class="pb-10 mx-8">
  <div class="container mx-auto mt-2">
    <%= form_for :search, Routes.search_path(conn_or_socket, :index), [method: :get], fn f -> %>
      <label class="flex flex-wrap block text-xl">
        <%= text_input f,
            :query,
            value: query,
            autofocus: true,
            placeholder: "search products by name or brand",
            class: "flex-grow border border-gray-400 rounded-tl-lg rounded-bl-lg pl-4 focus:border-gray-700" %>
        <%= submit "Search", class: "bg-gray-700 text-white px-4 rounded-tr-lg rounded-br-lg" %>
      </label>
    <% end %>
  </div>
</section>

apps/app/lib/app_web/templates/search/index.html.eex
<main>
  <%= render "_search_bar.html", assigns %>

  <!-- "Results" section -->
  <section class="pb-10 mx-8 mt-4">
    <div class="container">
      <h1 class="text-serif text-4xl text-purple-600 font-bold">
        <%= length(@products) %> <%= if length(@products) == 1 do %>result<% else %>results<% end %>
      </h1>
    </div>
    <div class="container mx-auto">
      <div class="grid lg:grid-cols-4 md:grid-cols-2 sm:grid-cols-2 grid-rows-auto gap-4">
        <%= for product <- @products do %>
          <div class="flex flex-col shadow p-4 border border-gray-200 rounded">
            <div class="h-48 flex items-center">
              <%= if image_url = product.main_thumbnail do %>
                <img src="<%= image_url %>" alt="<%= product.description %>" class="max-h-full m-auto">
              <% else %>
                <div class="h-full w-full bg-gray-200 flex items-center">
                  <div class="flex-grow text-center text-3xl text-gray-600 p-2"><%= product.description %></div>
                </div>
              <% end %>
            </div>
            <div class="mt-4 flex-grow">
              <div class="font-bold"><%= product.description %>, <%= product.units_per_case %> x <%= product.pack_size %><%= product.unit %></div>
              <div class="text-sm">by <%= product.brand %></div>
              <div class="mt-4 grid grid-rows-3 grid-rows-auto-min text-base" style="grid-template-columns: repeat(3, auto)">

                <div class="font-bold"><%= product.wholesaler %></div>
                <%= format_price(product.case_price) %>
                <i class="far fa-question-circle" title="This is the price the wholesaler is charging for a case"></i>

                <div class="font-bold">RRP (unit) </div>
                <%= format_price(Product.rrp_per_unit(product)) %>
                <i class="far fa-question-circle" title="This is the typical price you would see an item in shops (retail price)"></i>

                <div class="font-bold">RRP (case) </div>
                <%= format_price(Product.indicative_rrp_per_case(product)) %>
                <i class="far fa-question-circle" title="This is the price you would pay buying a whole case at retail price"></i>

              </div>
              </div>
            <div class="flex flex-row flex-wrap mt-4">
              <%= form_for :cart,
                  Routes.cart_path(@conn, :update, return_to: "#{@conn.request_path}?#{@conn.query_string}"),
                  [method: :post],
              fn f -> %>
                <%= if cart_line = product.cart_line do %>
                  <%= number_input f,
                  :qty,
                  value: cart_line.quantity,
                  min: 0,
                  class: "w-16 inline border border-gray-400 pl-4" %>
                <% else %>
                  <%= number_input f,
                  :qty,
                  value: 0,
                  min: 0,
                  class: "w-16 inline border border-gray-400 pl-4" %>
                <% end %>
                <%= hidden_input f, :product, value: product.id %>
                <%= if product.cart_line do %>
                  <%= submit "Update", class: "px-4 ml-2 underline" %>
                <% else %>
                  <%= submit "Add to cart", class: "px-4 underline" %>
                <% end %>
              <% end %>
              <%= if product.cart_line do %>
                <%= form_for :cart,
                    Routes.cart_path(@conn, :update, return_to: "#{@conn.request_path}?#{@conn.query_string}"),
                    [method: :post],
                    fn f -> %>
                  <%= hidden_input f, :qty, value: 0 %>
                  <%= hidden_input f, :product, value: product.id %>
                  <%= submit "Remove", class: "px-4 text-small text-red-500 underline" %>
                <% end %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </section>
</main>